project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="simar1"
admin.site.site_title="simar2"
admin.site.index_title= "simar3"

task/urls.py
from django.urls import path
from .views import image_view, success

app_name='task'

urlpatterns = [
	#path('', views.doc_list, name='doc_list'),
	path('', image_view, name = 'image_upload'), 
    path('success', success, name = 'success'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from task import views
from django.views.generic import RedirectView
from django.contrib.auth import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', RedirectView.as_view(pattern_name='person_changelist'), name='home'),
]
admin.site.site_header="simar1"
admin.site.site_title="simar2"
admin.site.index_title= "simar3"

task/models.py
from django.db import models
from .validators import validate_file_extension
from django.utils import timezone
from django.conf import settings
from django.utils.translation import ugettext_lazy as _ 
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
#from django.contrib.auth.models import User
from django.forms import ModelForm

class Article(models.Model):
	DRAFT='draft'
	PUBLISHED='published'
	
	STATUS_CHOICES = (
		(DRAFT,_("Draft")),
		(PUBLISHED,_("Published")),
		)

	author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	title=models.CharField(max_length=100,)
	body=models.TextField()
	status=models.CharField(choices=STATUS_CHOICES,default=DRAFT, max_length=10,)
	#file = models.FileField(upload_to="documents/%Y/%m/%d", validators=[validate_file_extension])

	def __str__(self):
		return self.title

class Art(models.Model):
    DRAFT='draft'
    PUBLISHED='published'
    
    STATUS_CHOICES = (
        (DRAFT,_("Draft")),
        (PUBLISHED,_("Published")),
        )

    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    title=models.CharField(max_length=100,)
    body=models.TextField()
    status=models.CharField(choices=STATUS_CHOICES,default=DRAFT, max_length=10,)
    #file = models.FileField(upload_to="documents/%Y/%m/%d", validators=[validate_file_extension])

    def __str__(self):
        return self.title


class Img(models.Model):
    image=models.ImageField(null=True, blank=True, upload_to='images/')
    




class MyUserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

task/forms.py
from django import forms
from .models import Article,Img


class ArticleForm(forms.ModelForm):
	class Meta:
		model=Article
		fields=('author','title','body')

class ImgForm(forms.ModelForm):
	class Meta:
		model=Img
		fields=('image',)
   

task/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from .models import Img
from .forms import *
from django.http import HttpResponse 

#def doc_list(request):
    #return render(request, 'task/doc_list.html')    

def image_view(request): 
  
    if request.method == 'POST': 
        form = ImgForm(request.POST, request.FILES) 
  
        if form.is_valid(): 
            form.save() 
            return redirect('task:success') 
    else: 
        form = ImgForm() 
    return render(request, 'task/doc_list.html', {'form' : form}) 
  
def success(request): 
    return render(request, 'task/base.html')

task/templates/task/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple ERP{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Simple ERP</h1>
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
         <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </body>
</html>

task/templates/task/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

task/templates/task/details_form.html
{% block content %}

  <h2>Person Form</h2>
  <form method="post" id="DetailsForm" action="{% url 'task:details_new' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_name">Enter Name:</label>  <input type="text" name="name" required maxlength="100" id="id_name" /><br>
    <label for="id_email">Enter Email:</label>  <input type="email" name="email" id="id_email" /><br>
    <label for="id_address">Enter Address:</label>  <input type="text" name="address" required maxlength="100" id="id_address" /><br>

    <label for="id_country">Enter Country:</label>
    <select>
    	<option value="">---------</option>
    {% for Country in country %}
		<option value="{{ Country.pk }}">{{ Country.name }}</option>
	{% endfor %}
    </select>
    <br>
    <label for="id_city">Enter City:</label>
    <select>
    	<option value="">---------</option>
    {% for city in cities %}
		<option value="{{ city.pk }}">{{ city.name }}</option>
	{% endfor %}
    </select>
    <br>
    <label for="id_zipcode">Enter Zip-Code:</label>  <input type="number" name="zipcode" required maxlength="10" id="id_zipcode" /><br>
    <label for="id_phone_number">Enter Phone:</label>  <input type="number" name="city" required maxlength="10" id="id_phone_number" /><br>
    <label for="id_image">Upload Image:</label>  <input type="file" name="imag" id="id_image" /><br>
    <button type="submit" class="save btn btn-default">Save</button><br>
  </form>

{% endblock %}

task/templates/task/details_list.html
{% extends 'task/base.html' %}
{% block content %}
  <p>
    <a href="{% url 'person_add' %}">Add person</a>
  </p>
  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
        <tr>
          <td><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.country.name }}</td>
          <td>{{ person.city.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'person_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

task/templates/task/doc_list.html
<html lang="en"> 
<head>  
    <title>Hotel_image</title> 
</head> 
<body> 
   <form method="POST" class="post-form" enctype="multipart/form-data">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit" class="save btn btn-default">Save</button>  
</form>  
</body> 
</html> 